# Generated by Django 4.0.4 on 2022-04-11 16:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=100000)),
                ('blog_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('blog_content', models.CharField(max_length=1000000000000)),
                ('first_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('second_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('third_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('fourth_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('fifth_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('sixth_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('seventh_image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myblog.blog')),
            ],
        ),
    ]
