# Generated by Django 4.0.4 on 2022-04-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='fifth_image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='fourth_image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='second_image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='seventh_image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='sixth_image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='third_image',
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_content',
            field=models.TextField(),
        ),
    ]
